language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag numgeom/desktop-base:16.04 numgeom/desktop-base:latest . && docker push numgeom/desktop-base
  - git clone -b cuda https://github.com/fastsolve/desktop-base.git cuda && docker build --tag numgeom/desktop-base:cuda cuda && docker push numgeom/desktop-base:cuda
  - docker images
