os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=compdatasci/octave-desktop:latest
  matrix:
    - XVFB=1 VERSION=17F
    - XVFB=0 VERSION=17F

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] || [[ "$XVFB" != "1" ]] ||
    (docker build --tag ams595/desktop:$VERSION
                  --tag ams595/desktop:latest . &&
     docker push ams595/desktop &&
     touch success)'
  # Test startup scripts
  - './ams595_desktop.py -d -n && docker stop $(docker ps -q) &&
     ./ams595_jupyter.py -d -n && docker stop $(docker ps -q)'
  - docker images
