language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag numgeom/desktop-base . && docker push numgeom/desktop-base
  - docker images
