os: linux
dist: trusty
sudo: required
language: python

before_install:
  # Install latest version of docker-ce
  - curl -O https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_17.05.0~ce-0~ubuntu-trusty_amd64.deb
  - sudo dpk -i docker-engine_17.05.0~ce-0~ubuntu-trusty_amd64.deb

  # Start up xvfb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] ||
    (docker build --tag ams595/desktop:16.04 --tag ams595/desktop:latest . &&
     touch success)'
  # Test startup scripts
  - './ams595_desktop.py -d && docker stop $(docker ps -q) &&
     ./ams595_jupyter.py -d && docker stop $(docker ps -q) &&
     ([[ ! -f success ]] || docker push ams595/desktop)'
  - docker images
